### ISSUE TITLE
Suggestion: add defer off-screen images for better performance

### ISSUE THREAD

**Issue by 8ctopus** [xenocrat/chyrp-markdown#1]
I understand that this suggestion has nothing to do with the markdown to html conversion, however since the generated html is going to be most likely displayed. It would make sense to defer off-screen images as well as indicate width and height.

Maybe this could come as a parser option or a derived parser?

**Comment by xenocrat** [comment]
Hello there,

Thanks for the suggestion. Lazy-loading can be added easily as a global toggle but image dimensions would require extended syntax.

In general I don't want to go beyond the features offered by the supported Markdown flavours, but perhaps adding intrinsic dimensions to images is a good exception to that rule. I'm toying with `![alt](URL){width:height}` as an extended syntax.

**Comment by 8ctopus** [comment]
I like it.

**Comment by 8ctopus** [comment]
Thank you!

**Comment by xenocrat** [comment]
You're welcome. Thank you for the suggestion! ^_^
